import json

# Read input
with open('ctx_input/chunk_08.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Label assignments: (word, meaning_index) -> labels
labels = {
    "gentleman": {
        1: "formal, social",
        2: "social, formal",
        3: "general, social",
        4: "finance, social",
        5: "formal, communication",
        6: "daily life",
    },
    "geography": {
        1: "education, geography",
    },
    "get": {
        1: "general",
        2: "general, communication",
        3: "general, education",
        4: "shopping",
        5: "education",
        6: "health, general",
        7: "food",
        8: "animals, farming",
        9: "communication, education",
        10: "daily life, transportation",
        11: "general",
        12: "general",
        13: "general",
        14: "communication, work",
        15: "general",
        16: "animals",
        17: "shopping, work",
        18: "travel, transportation",
        19: "general",
        20: "general",
        21: "informal, daily life",
    },
    "ghost": {
        1: "entertainment, culture",
        2: "appearance, informal",
        3: "appearance, general",
        4: "literature, work",
        5: "religion, philosophy",
        6: "feelings, emotions",
        7: "literature, work",
    },
    "giant": {
        1: "general, animals",
        2: "general, success",
        3: "general",
        4: "general, success",
    },
    "gift": {
        1: "general, social",
        2: "shopping, social",
        3: "personality, success",
        4: "social, general",
        5: "general",
    },
    "girl": {
        1: "family",
        2: "home, work",
        3: "relationships, love",
    },
    "girlfriend": {
        1: "relationships",
        2: "relationships, love",
    },
    "give": {
        1: "social, general",
        2: "general",
        3: "general, communication",
        4: "health, communication",
        5: "money, shopping",
        6: "general",
        7: "general",
        8: "work, feelings",
        9: "entertainment, arts, music",
        10: "general",
        11: "general",
        12: "communication",
        13: "communication, formal",
        14: "general",
        15: "law",
        16: "general",
    },
    "glad": {
        1: "feelings, emotions",
    },
    "glass": {
        1: "general, home",
        2: "home, daily life",
        3: "food, daily life",
        4: "weather, home",
        5: "clothing, daily life",
        6: "technology, daily life",
        7: "home, daily life",
        8: "plants, home",
        9: "home, appearance",
        10: "time, home",
        11: "health, clothing",
        12: "home, construction",
        13: "appearance, home",
        14: "home",
    },
    "global": {
        1: "geography, general",
        2: "general",
        3: "general",
    },
    "glove": {
        1: "clothing",
        2: "clothing, daily life",
    },
    "go": {
        1: "travel, transportation",
        2: "general",
        3: "time",
        4: "health, general",
        5: "general",
        6: "technology, transportation",
        7: "time, military",
        8: "general",
        9: "general",
        10: "finance, business",
        11: "general",
        12: "money, finance",
        13: "home, daily life",
        14: "general",
        15: "communication, social",
        16: "daily life, body",
        17: "money, shopping",
        18: "general",
        19: "communication",
        20: "music, arts",
        21: "feelings, emotions",
        22: "sports, games",
        23: "relationships, social",
        24: "communication",
        25: "games, money",
        26: "general, transportation",
        27: "feelings, personality",
        28: "general",
        29: "general",
        30: "general",
        31: "food, restaurant",
        32: "general",
        33: "success",
        34: "work, daily life",
        35: "general",
    },
    "goal": {
        1: "sports",
        2: "sports",
        3: "success, general",
    },
    "god": {
        1: "religion",
        2: "entertainment, sports",
        3: "religion, feelings",
        4: "religion",
        5: "religion",
        6: "religion",
        7: "religion",
        8: "religion, informal",
        9: "religion, emotions",
        10: "religion",
        11: "religion",
        12: "religion",
        13: "religion",
        14: "religion, literature",
        15: "general, social",
    },
    "gold": {
        1: "money, shopping",
        2: "money, finance",
        3: "money, finance",
        4: "general, appearance",
        5: "money, general",
        6: "money, general",
        7: "general, appearance",
    },
    "golf": {
        1: "sports",
        2: "sports",
    },
    "good": {
        1: "general",
        2: "personality, feelings",
        3: "food",
        4: "health",
        5: "work, success",
        6: "feelings, daily life",
        7: "general",
        8: "finance, business",
        9: "general",
        10: "general, personality",
    },
    "goodbye": {
        1: "communication, social",
        2: "communication, social",
    },
    "goods": {
        1: "finance, business",
        2: "business, shopping",
        3: "transportation, business",
    },
    "govern": {
        1: "government, politics",
        2: "management, government",
        3: "feelings, psychology",
        4: "general",
        5: "general",
        6: "general",
    },
    "government": {
        1: "government, politics",
        2: "government, politics",
        3: "government, politics",
        4: "government, politics",
        5: "government, geography",
        6: "government, management",
        7: "general",
        8: "general",
    },
    "governor": {
        1: "government, politics",
        2: "government, politics",
        3: "education, health",
        4: "management, work",
        5: "family",
        6: "technology, engineering",
    },
    "grab": {
        1: "general",
        2: "crime, law",
        3: "construction, industry",
        4: "games, daily life",
        5: "general",
        6: "crime, law",
    },
    "grade": {
        1: "general",
        2: "work, education",
        3: "education",
        4: "education",
        5: "geography, general",
        6: "animals, farming",
        7: "general",
        8: "construction",
        9: "general",
        10: "farming, animals",
        11: "arts, design",
        12: "general",
    },
    "gradually": {
        1: "general, time",
    },
    "graduate": {
        1: "general",
        2: "general",
        3: "general",
        4: "general",
        5: "general",
        6: "general",
        7: "education",
        8: "education",
        9: "general",
        10: "education, work",
    },
    "grain": {
        1: "food, farming",
        2: "general, food",
        3: "general",
        4: "construction, nature",
        5: "personality, psychology",
        6: "general",
        7: "arts, literature",
        8: "food, cooking",
        9: "cooking, food",
        10: "general",
        11: "design, arts",
        12: "arts, design",
        13: "clothing, animals",
        14: "clothing, animals",
        15: "general",
    },
    "grand": {
        1: "general",
        2: "formal, appearance",
        3: "formal, social",
        4: "success, general",
        5: "general",
        6: "general",
        7: "music, arts",
        8: "money, finance",
        9: "money, finance",
    },
    "grandfather": {
        1: "family",
    },
    "grandmother": {
        1: "family",
        2: "family, feelings",
    },
    "grandparent": {
        1: "family",
    },
    "grant": {
        1: "general",
        2: "money, education",
        3: "law, finance",
        4: "law, finance",
        5: "general",
        6: "general",
        7: "law, finance",
    },
    "grass": {
        1: "plants, nature",
        2: "nature, plants",
        3: "nature, urban",
        4: "plants, nature",
        5: "nature, geography",
        6: "food, plants",
        7: "time, nature",
        8: "farming, plants",
        9: "informal, general",
        10: "animals, hunting",
        11: "daily life, clothing",
    },
    "grateful": {
        1: "feelings, emotions",
        2: "feelings, health",
    },
    "gray": {
        1: "general",
        2: "general",
        3: "general",
    },
    "great": {
        1: "general",
        2: "general",
        3: "formal, social",
        4: "general, feelings",
        5: "education, work",
        6: "family, social",
        7: "history, education",
    },
    "green": {
        1: "general, appearance",
        2: "food, nature",
        3: "feelings, time",
        4: "work, personality",
        5: "health, body",
        6: "feelings, emotions",
        7: "health, body",
        8: "general, appearance",
        9: "clothing",
        10: "arts, design",
        11: "plants, nature",
        12: "nature, plants",
        13: "food, cooking",
        14: "time, health",
        15: "personality, feelings",
        16: "general",
        17: "arts, design",
        18: "informal, communication",
    },
    "greet": {
        1: "communication, social",
        2: "social, feelings",
        3: "general, feelings",
        4: "feelings, emotions",
    },
    "grocery": {
        1: "shopping, business",
        2: "shopping, business",
        3: "shopping, food",
    },
    "ground": {
        1: "general",
        2: "nature, geography",
        3: "nature, farming",
        4: "home, nature",
        5: "geography, general",
        6: "nature, geography",
        7: "general, arts",
        8: "general",
        9: "general, communication",
        10: "technology, electricity",
        11: "travel, transportation",
        12: "communication, work",
        13: "communication, general",
        14: "animals, hunting",
        15: "general",
        16: "general",
        17: "education",
        18: "arts, design",
        19: "general",
        20: "transportation, travel",
        21: "transportation, military",
        22: "technology, electricity",
        23: "transportation, travel",
        24: "transportation, travel",
        25: "cooking, food",
    },
    "group": {
        1: "general, social",
        2: "general, social",
        3: "general, teamwork",
        4: "general, work",
        5: "arts, design",
    },
    "grow": {
        1: "plants, nature",
        2: "body, family",
        3: "general, business",
        4: "general",
        5: "farming, plants",
        6: "appearance, body",
    },
    "growth": {
        1: "general, business",
        2: "general, business",
        3: "body, health",
        4: "farming, food",
        5: "general",
        6: "health, medicine",
    },
    "guarantee": {
        1: "business, law",
        2: "business, law",
        3: "business, law",
        4: "business, law",
        5: "general",
        6: "business, law",
        7: "general",
    },
    "guard": {
        1: "sports",
        2: "safety, general",
        3: "safety, technology",
        4: "military, safety",
        5: "safety, military",
        6: "crime, law",
        7: "military",
        8: "transportation, work",
        9: "safety, general",
        10: "safety, general",
        11: "technology, safety",
    },
    "guess": {
        1: "general",
        2: "general",
        3: "informal, general",
    },
    "guest": {
        1: "social, general",
        2: "travel, hotel",
        3: "animals, plants",
    },
    "guide": {
        1: "tourism, travel",
        2: "education, general",
        3: "education, literature",
        4: "travel, transportation",
        5: "technology, engineering",
        6: "military",
        7: "transportation, military",
        8: "travel, general",
    },
    "guilty": {
        1: "crime, law",
        2: "crime, law",
    },
    "guitar": {
        1: "music, arts",
        2: "music, arts",
    },
    "gun": {
        1: "military, crime",
        2: "military",
        3: "military, crime",
        4: "sports, hunting",
        5: "military",
        6: "technology, industry",
        7: "farming, technology",
        8: "crime, informal",
        9: "crime, law",
    },
    "guy": {
        1: "general",
        2: "general",
        3: "informal, personality",
        4: "appearance, informal",
        5: "informal, social",
        6: "informal, daily life",
        7: "informal, communication",
        8: "informal, communication",
        9: "informal, communication",
        10: "informal, daily life",
    },
    "gym": {
        1: "sports, exercise",
        2: "sports, exercise",
    },
    "habit": {
        1: "daily life, psychology",
        2: "body, appearance",
        3: "personality, psychology",
        4: "general",
        5: "clothing, sports",
        6: "clothing, religion",
        7: "clothing, daily life",
        8: "home, daily life",
    },
    "hair": {
        1: "body, appearance",
        2: "appearance, informal",
    },
    "half": {
        1: "general",
        2: "time",
        3: "money, work",
        4: "education, time",
        5: "general",
        6: "general",
        7: "general",
    },
    "hall": {
        1: "home, history",
        2: "home, history",
        3: "home, music",
        4: "government, law",
        5: "education, food",
        6: "education, home",
        7: "home, daily life",
    },
    "hand": {
        1: "body, animals",
        2: "work, management",
        3: "work, general",
        4: "marriage, relationships",
        5: "work, industry",
        6: "transportation, work",
        7: "work, general",
        8: "general",
        9: "general, work",
        10: "education, communication",
        11: "time, general",
        12: "food, plants",
        13: "general",
        14: "animals, measurement",
        15: "general, geography",
        16: "games, entertainment",
        17: "entertainment, social",
        18: "general, communication",
        19: "general, daily life",
        20: "transportation, daily life",
    },
    "handle": {
        1: "general, daily life",
        2: "general",
        3: "formal, work",
        4: "general, daily life",
        5: "general, work",
        6: "communication, social",
        7: "education, work",
        8: "management, work",
        9: "business, shopping",
    },
    "hang": {
        1: "general",
        2: "geography, nature",
        3: "home, daily life",
        4: "general, communication",
        5: "home, daily life",
        6: "crime, law",
        7: "home, daily life",
        8: "feelings, body",
        9: "general",
        10: "crime, law",
        11: "general",
        12: "general",
    },
    "happen": {
        1: "general",
        2: "general",
        3: "general, social",
    },
    "happily": {
        1: "feelings, emotions",
        2: "feelings, emotions",
        3: "communication, general",
    },
    "happiness": {
        1: "feelings, emotions",
        2: "communication, literature",
        3: "feelings, general",
    },
    "happy": {
        1: "feelings, social",
        2: "feelings, general",
        3: "feelings, emotions",
        4: "communication, social",
        5: "military, health",
    },
    "hard": {
        1: "general",
        2: "general",
        3: "general",
        4: "personality, feelings",
        5: "personality, feelings",
        6: "general",
        7: "general, work",
        8: "general",
        9: "finance, business",
        10: "general",
        11: "money, finance",
        12: "food, drink",
        13: "work, personality",
        14: "general",
        15: "personality, feelings",
        16: "general, work",
        17: "general",
        18: "transportation, travel",
        19: "history, crime",
    },
    "hardly": {
        1: "general",
        2: "general",
        3: "general",
        4: "personality, feelings",
        5: "personality, feelings",
        6: "general",
        7: "general, work",
        8: "general",
        9: "finance, business",
        10: "general",
        11: "money, finance",
        12: "food, drink",
        13: "work, personality",
        14: "general",
        15: "personality, feelings",
        16: "general, work",
        17: "general",
        18: "transportation, travel",
        19: "history, crime",
    },
    "harm": {
        1: "general",
        2: "crime, general",
        3: "general",
    },
    "harmful": {
        1: "health, general",
    },
    "hat": {
        1: "clothing",
        2: "clothing, daily life",
    },
    "hate": {
        1: "feelings, emotions",
        2: "feelings, emotions",
        3: "feelings, general",
    },
    "have": {
        1: "general",
        2: "general",
        3: "food, daily life",
        4: "general",
        5: "general",
        6: "education, general",
        7: "communication, general",
        8: "success, competition",
        9: "general",
        10: "communication, work",
        11: "informal, communication",
        12: "general",
        13: "informal, communication",
    },
    "have to": {
        1: "general, work",
    },
    "he": {
        1: "general",
        2: "general, animals",
        3: "animals",
        4: "religion",
    },
    "head": {
        1: "body, animals",
        2: "animals, general",
        3: "education, psychology",
        4: "health, food",
        5: "work, management",
        6: "general",
        7: "general",
        8: "general",
        9: "food, drink",
        10: "health, body",
        11: "animals",
        12: "transportation",
        13: "geography, nature",
        14: "money, finance",
        15: "transportation, construction",
        16: "transportation",
        17: "education, communication",
        18: "general, feelings",
        19: "technology, general",
        20: "general",
        21: "plants, farming",
        22: "education, communication",
        23: "work, management",
        24: "general, competition",
        25: "success, competition",
        26: "geography, travel",
        27: "sports",
        28: "general",
        29: "transportation, travel",
        30: "plants, food",
        31: "health, body",
        32: "travel, transportation",
    },
    "headache": {
        1: "health, medicine",
        2: "general, work",
    },
    "headline": {
        1: "media, communication",
        2: "media, communication",
        3: "media, communication",
        4: "media, business",
    },
    "health": {
        1: "health",
        2: "health",
        3: "health, exercise",
        4: "food, drink",
        5: "health, medicine",
    },
    "healthy": {
        1: "health",
        2: "health",
        3: "health, exercise",
        4: "food, drink",
        5: "health, medicine",
    },
    "hear": {
        1: "general, communication",
        2: "communication, general",
        3: "communication, media",
    },
    "hearing": {
        1: "health, body",
        2: "general",
        3: "general, communication",
    },
    "heart": {
        1: "body, health",
        2: "body",
        3: "feelings, emotions",
        4: "feelings, love",
        5: "feelings, personality",
        6: "relationships, family",
        7: "general",
        8: "general",
        9: "general",
        10: "farming, nature",
        11: "games, entertainment",
        12: "general",
    },
    "heat": {
        1: "weather, general",
        2: "science, general",
        3: "weather",
        4: "health, body",
        5: "food, cooking",
        6: "general, feelings",
        7: "feelings, emotions",
        8: "animals",
        9: "work, sports",
        10: "sports, competition",
        11: "industry, cooking",
        12: "crime, law",
        13: "cooking, general",
        14: "feelings, emotions",
        15: "feelings, general",
        16: "industry, cooking",
        17: "general",
        18: "feelings, emotions",
        19: "general",
    },
    "heating": {
        1: "general",
        2: "home, daily life",
        3: "science, industry",
    },
    "heaven": {
        1: "religion",
        2: "religion",
        3: "nature, weather",
        4: "feelings, religion",
    },
    "heavily": {
        1: "general",
    },
    "heavy": {
        1: "general",
        2: "general",
        3: "food",
        4: "general",
        5: "general",
        6: "general",
        7: "food, cooking",
        8: "arts, literature",
        9: "feelings, weather",
        10: "transportation, travel",
        11: "personality, psychology",
        12: "appearance, personality",
        13: "feelings, emotions",
        14: "health, body",
        15: "personality, formal",
        16: "general",
        17: "general",
        18: "general",
        19: "military, history",
        20: "military",
        21: "sports",
        22: "entertainment, arts",
    },
    "heel": {
        1: "body",
        2: "animals",
        3: "clothing",
        4: "music, sports",
        5: "transportation",
        6: "informal, social",
        7: "clothing, daily life",
        8: "general",
        9: "sports",
        10: "sports",
        11: "entertainment, sports",
        12: "transportation",
    },
    "height": {
        1: "general, body",
        2: "general",
        3: "general, success",
    },
    "helicopter": {
        1: "transportation, military",
    },
    "hell": {
        1: "religion",
        2: "games, daily life",
        3: "entertainment, crime",
        4: "informal, religion",
    },
    "hello": {
        1: "communication, social",
        2: "communication, technology",
        3: "communication, informal",
        4: "communication, emotions",
        5: "communication, social",
        6: "communication, informal",
        7: "communication, emotions",
        8: "communication, social",
        9: "communication, informal",
        10: "communication, emotions",
    },
    "help": {
        1: "general, social",
        2: "general",
        3: "food, restaurant",
        4: "home, work",
        5: "general, social",
        6: "food, restaurant",
        7: "general",
    },
    "helpful": {
        1: "general, social",
    },
    "her": {
        1: "general",
        2: "general",
    },
    "here": {
        1: "general",
        2: "general",
    },
    "hero": {
        1: "general, entertainment",
        2: "literature, arts",
    },
    "hers": {
        1: "general",
        2: "general",
    },
    "herself": {
        1: "general",
    },
    "hesitate": {
        1: "feelings, personality",
    },
    "hey": {
        1: "communication, emotions",
        2: "communication, informal",
    },
    "hi": {
        1: "communication, informal",
    },
    "hide": {
        1: "clothing, animals",
        2: "body, clothing",
        3: "animals, clothing",
        4: "crime, informal",
        5: "geography, farming",
        6: "animals, hunting",
        7: "general",
        8: "general",
        9: "general",
    },
    "high": {
        1: "general",
        2: "money, finance",
        3: "general, formal",
        4: "formal, social",
        5: "feelings, general",
        6: "formal, social",
        7: "personality",
        8: "feelings, personality",
        9: "general",
        10: "general",
        11: "time, general",
        12: "health, informal",
        13: "general",
        14: "general",
        15: "feelings, general",
        16: "formal, social",
        17: "general",
        18: "games",
        19: "nature, geography",
    },
    "highlight": {
        1: "arts, design",
        2: "general, media",
        3: "general, communication",
    },
    "highly": {
        1: "general",
        2: "money, finance",
        3: "general, formal",
        4: "formal, social",
        5: "feelings, general",
        6: "formal, social",
        7: "personality",
        8: "feelings, personality",
        9: "general",
        10: "general",
        11: "time, general",
        12: "health, informal",
        13: "general",
        14: "general",
        15: "feelings, general",
        16: "formal, social",
        17: "general",
        18: "games",
        19: "nature, geography",
        20: "general",
    },
    "highway": {
        1: "transportation, travel",
        2: "transportation, travel",
        3: "general",
    },
    "hill": {
        1: "geography, nature",
        2: "nature, geography",
        3: "tourism, nature",
        4: "construction, farming",
        5: "farming, plants",
    },
    "him": {
        1: "general",
    },
    "himself": {
        1: "general",
    },
    "hire": {
        1: "work, business",
        2: "work, business",
        3: "money, work",
        4: "home, business",
        5: "work, business",
        6: "money, work",
    },
    "his": {
        1: "weather, nature",
        2: "general",
    },
    "historic": {
        1: "history",
    },
    "historical": {
        1: "history",
    },
    "history": {
        1: "history, education",
        2: "history",
        3: "history, literature",
    },
    "hit": {
        1: "sports, general",
        2: "success, general",
        3: "communication, feelings",
        4: "sports, general",
        5: "general",
        6: "feelings, emotions",
        7: "general",
        8: "general",
        9: "general",
        10: "feelings, general",
        11: "general",
        12: "general",
    },
    "hobby": {
        1: "hobby, leisure",
        2: "animals",
        3: "transportation, daily life",
        4: "animals",
    },
    "hockey": {
        1: "sports",
    },
    "hold": {
        1: "transportation",
        2: "general",
        3: "general",
        4: "general",
        5: "general",
        6: "military, history",
        7: "crime, law",
        8: "crime, law",
        9: "general",
        10: "general",
        11: "general",
        12: "crime, law",
        13: "general",
        14: "general",
        15: "feelings, general",
        16: "general",
        17: "law",
        18: "general, work",
        19: "communication, general",
        20: "general",
        21: "general",
        22: "general",
        23: "general",
        24: "general",
        25: "communication, general",
    },
    "hole": {
        1: "general",
        2: "sports, games",
        3: "nature, geography",
        4: "animals",
        5: "home, daily life",
        6: "sports",
        7: "general",
        8: "general",
        9: "general",
        10: "general",
        11: "general",
        12: "sports, games",
        13: "construction, general",
        14: "general",
        15: "sports",
        16: "construction, mining",
        17: "animals",
    },
    "holiday": {
        1: "holiday, leisure",
        2: "holiday, leisure",
        3: "holiday, leisure",
        4: "holiday, leisure",
    },
    "hollow": {
        1: "general",
        2: "body, feelings",
        3: "general",
        4: "general",
        5: "general",
        6: "personality, feelings",
        7: "general",
        8: "general",
        9: "nature, geography",
        10: "geography, nature",
        11: "general",
        12: "general",
    },
    "holy": {
        1: "general",
        2: "religion",
    },
    "home": {
        1: "home",
        2: "home, family",
        3: "home, geography",
        4: "animals, nature",
        5: "home, health",
        6: "games, sports",
        7: "home, family",
        8: "home, geography",
        9: "geography, general",
        10: "home, daily life",
        11: "general",
        12: "technology, computing",
        13: "technology, computing",
        14: "technology, internet",
        15: "home, daily life",
        16: "home, travel",
        17: "games, sports",
        18: "general",
        19: "home, animals",
        20: "home, family",
        21: "home, daily life",
        22: "home, family",
    },
    "homework": {
        1: "education",
        2: "home, work",
    },
    "honest": {
        1: "personality, feelings",
        2: "personality, feelings",
        3: "work, finance",
        4: "shopping, general",
        5: "general",
        6: "relationships, general",
    },
    "honor": {
        1: "general",
        2: "formal, general",
        3: "formal, feelings",
        4: "feelings, formal",
        5: "relationships, general",
        6: "formal, work",
        7: "formal, military",
        8: "formal, religion",
        9: "education, formal",
        10: "formal, communication",
        11: "feelings, formal",
        12: "formal, general",
        13: "business, finance",
    },
    "hope": {
        1: "feelings, emotions",
        2: "feelings, general",
        3: "feelings, emotions",
    },
    "horrible": {
        1: "feelings, general",
        2: "feelings, general",
        3: "feelings, informal",
    },
    "horror": {
        1: "feelings, entertainment",
        2: "general, entertainment",
        3: "feelings, general",
        4: "feelings, body",
        5: "feelings, health",
    },
    "horse": {
        1: "animals",
        2: "military, animals",
        3: "sports, exercise",
        4: "home, daily life",
        5: "animals, mythology",
        6: "general",
        7: "mining, geology",
        8: "technology, engineering",
        9: "education, informal",
        10: "sports, animals",
        11: "animals",
        12: "informal, entertainment",
        13: "military, animals",
        14: "transportation, animals",
        15: "general, daily life",
        16: "crime, informal",
        17: "informal, entertainment",
    },
    "hospital": {
        1: "health, medicine",
        2: "health, general",
    },
    "host": {
        1: "home, social",
        2: "home, travel",
        3: "media, entertainment",
        4: "animals, plants",
        5: "general",
        6: "military, religion",
        7: "religion",
        8: "technology, internet",
        9: "home, social",
        10: "media, entertainment",
        11: "technology, internet",
    },
    "hot": {
        1: "weather, general",
        2: "food, cooking",
        3: "animals, hunting",
        4: "general",
        5: "feelings, general",
        6: "media, general",
        7: "money, crime",
        8: "feelings, general",
        9: "sports, competition",
        10: "crime, general",
        11: "military",
        12: "science, technology",
        13: "informal, relationships",
        14: "crime, informal",
        15: "crime, law",
        16: "crime, law",
        17: "general",
        18: "feelings, emotions",
        19: "general",
        20: "cooking, general",
    },
    "hotel": {
        1: "travel, tourism",
    },
    "hour": {
        1: "time",
        2: "time",
        3: "work, time",
        4: "religion, time",
    },
    "house": {
        1: "home",
        2: "home, animals",
        3: "travel, food",
        4: "government, politics",
        5: "entertainment, arts",
        6: "religion",
        7: "business, finance",
        8: "finance, business",
        9: "religion",
        10: "education, home",
        11: "family, history",
        12: "entertainment, finance",
        13: "animals, home",
        14: "home, social",
        15: "home, business",
        16: "home, social",
        17: "military, technology",
        18: "transportation",
        19: "construction, home",
        20: "home, daily life",
    },
    "household": {
        1: "home, family",
        2: "home, family",
        3: "general",
        4: "home, family",
    },
    "housing": {
        1: "general",
        2: "home, social",
        3: "home, business",
        4: "home, social",
        5: "home",
        6: "animals, clothing",
    },
    "how": {
        1: "general, communication",
        2: "money, general",
        3: "general, feelings",
        4: "general",
        5: "general",
        6: "general, work",
    },
    "however": {
        1: "general",
        2: "general, communication",
    },
    "huge": {
        1: "general",
    },
    "human": {
        1: "general",
        2: "feelings, personality",
        3: "general",
    },
    "humor": {
        1: "entertainment, feelings",
        2: "entertainment, personality",
        3: "personality, feelings",
        4: "general",
        5: "health, body",
        6: "social, communication",
    },
    "humorous": {
        1: "entertainment, feelings",
    },
    "hundred": {
        1: "general",
        2: "general",
        3: "geography, general",
    },
    "hungry": {
        1: "food, body",
        2: "food, general",
        3: "feelings, general",
        4: "general",
    },
    "hunt": {
        1: "animals, sports",
        2: "general",
        3: "animals, sports",
        4: "animals, geography",
        5: "animals, sports",
        6: "general",
        7: "animals, sports",
        8: "general",
        9: "animals, sports",
    },
    "hunting": {
        1: "animals, sports",
        2: "general",
        3: "animals, sports",
        4: "general",
    },
    "hurricane": {
        1: "weather, nature",
        2: "general, weather",
    },
    "hurry": {
        1: "general, daily life",
        2: "feelings, general",
        3: "communication, work",
        4: "work, daily life",
        5: "daily life, transportation",
        6: "daily life, general",
    },
    "hurt": {
        1: "health, body",
        2: "general",
        3: "feelings, emotions",
        4: "health, body",
        5: "general",
        6: "feelings, emotions",
        7: "health, body",
        8: "feelings, general",
    },
    "husband": {
        1: "marriage, family",
        2: "home, finance",
        3: "farming, work",
        4: "finance, daily life",
        5: "marriage, informal",
        6: "marriage, family",
        7: "farming, work",
    },
    "I": {
        1: "general",
        2: "general",
        3: "general",
        4: "general",
    },
    "ice": {
        1: "nature, weather",
        2: "food",
        3: "money, informal",
        4: "personality, feelings",
        5: "crime, informal",
        6: "entertainment, crime",
        7: "cooking, food",
        8: "nature, weather",
        9: "food, drink",
        10: "food, cooking",
        11: "sports",
        12: "nature, weather",
        13: "nature, weather",
    },
    "ice cream": {
        1: "food",
    },
    "idea": {
        1: "general, education",
        2: "education, general",
        3: "general, psychology",
        4: "general, work",
        5: "philosophy, education",
    },
    "ideal": {
        1: "philosophy, general",
        2: "general, philosophy",
        3: "general, philosophy",
        4: "philosophy",
        5: "philosophy",
        6: "general, philosophy",
        7: "general",
        8: "philosophy, general",
    },
    "identify": {
        1: "general",
        2: "general, communication",
        3: "feelings, social",
    },
    "identity": {
        1: "general, law",
        2: "general, personality",
        3: "philosophy, general",
    },
    "if": {
        1: "general",
        2: "general",
        3: "general, time",
        4: "general, feelings",
        5: "general",
        6: "general",
        7: "general",
    },
    "ignore": {
        1: "communication, social",
        2: "law, crime",
    },
    "ill": {
        1: "health, medicine",
        2: "general",
        3: "general",
        4: "general",
        5: "general",
        6: "feelings, general",
        7: "general",
        8: "general",
        9: "general",
        10: "general",
    },
    "illegal": {
        1: "law, crime",
    },
}

# Generate output
lines = []
for item in data:
    word = item["word"]
    meanings = item["meanings"]
    for i, meaning in enumerate(meanings, 1):
        if word in labels and i in labels[word]:
            label_str = ", ".join(labels[word][i])
        else:
            label_str = "general"
        lines.append(f"{word}\t{i}\t{label_str}")

# Write output
with open('ctx_parts/run3/chunk_08.txt', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')

print(f"words={len(data)} meanings={sum(len(d['meanings']) for d in data)} lines={len(lines)}")
