import json

# Read input
with open('E:/vibe_coding/english-app/ctx_input/chunk_14.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Label assignments: (word, meaning_index) -> [labels]
labels = {
    # quit
    ("quit", 1): ["work", "daily life"],
    # relatively
    ("relatively", 1): ["general"],
    ("relatively", 2): ["general"],
    ("relatively", 3): ["relationships", "family"],
    ("relatively", 4): ["general"],
    ("relatively", 5): ["family", "relationships"],
    ("relatively", 6): ["education"],
    # quite
    ("quite", 1): ["general"],
    # relax
    ("relax", 1): ["health", "body"],
    ("relax", 2): ["health", "feelings"],
    ("relax", 3): ["health", "leisure"],
    ("relax", 4): ["law"],
    ("relax", 5): ["health"],
    ("relax", 6): ["health", "medicine"],
    ("relax", 7): ["body", "health"],
    ("relax", 8): ["feelings", "health"],
    ("relax", 9): ["leisure", "hobby"],
    # quotation
    ("quotation", 1): ["literature", "education"],
    ("quotation", 2): ["finance", "business"],
    ("quotation", 3): ["business", "shopping"],
    ("quotation", 4): ["general"],
    # relaxed
    ("relaxed", 1): ["general"],
    ("relaxed", 2): ["feelings", "health"],
    # quote
    ("quote", 1): ["literature", "education"],
    ("quote", 2): ["literature", "education"],
    ("quote", 3): ["literature", "education"],
    ("quote", 4): ["literature", "education"],
    ("quote", 5): ["business", "shopping"],
    # relaxing
    ("relaxing", 1): ["general"],
    ("relaxing", 2): ["health", "feelings"],
    # race
    ("race", 1): ["family", "history"],
    ("race", 2): ["society", "culture"],
    ("race", 3): ["animals", "plants"],
    ("race", 4): ["family", "history"],
    ("race", 5): ["society", "culture"],
    ("race", 6): ["plants", "food"],
    ("race", 7): ["food", "plants"],
    ("race", 8): ["sports", "competition"],
    ("race", 9): ["sports", "entertainment"],
    ("race", 10): ["nature", "environment"],
    ("race", 11): ["nature", "environment"],
    ("race", 12): ["philosophy", "general"],
    ("race", 13): ["science", "nature"],
    ("race", 14): ["engineering", "technology"],
    ("race", 15): ["sports", "competition"],
    ("race", 16): ["sports", "transportation"],
    ("race", 17): ["sports", "transportation"],
    ("race", 18): ["work", "time"],
    ("race", 19): ["sports", "competition"],
    ("race", 20): ["transportation", "technology"],
    ("race", 21): ["sports", "hobby"],
    # release
    ("release", 1): ["health", "feelings"],
    ("release", 2): ["law", "crime"],
    ("release", 3): ["media", "business"],
    ("release", 4): ["business", "finance"],
    ("release", 5): ["law", "business"],
    ("release", 6): ["general"],
    ("release", 7): ["technology", "home"],
    ("release", 8): ["general"],
    ("release", 9): ["military"],
    ("release", 10): ["military"],
    ("release", 11): ["general"],
    ("release", 12): ["health", "feelings"],
    ("release", 13): ["law", "crime"],
    ("release", 14): ["law", "finance"],
    ("release", 15): ["media", "business"],
    ("release", 16): ["business", "law"],
    ("release", 17): ["media", "literature"],
    ("release", 18): ["technology", "general"],
    ("release", 19): ["military"],
    ("release", 20): ["military"],
    ("release", 21): ["general"],
    # relevant
    ("relevant", 1): ["general", "work"],
    # racing
    ("racing", 1): ["sports", "competition"],
    ("racing", 2): ["education"],
    # reliable
    ("reliable", 1): ["general", "work"],
    # radio
    ("radio", 1): ["media", "technology"],
    ("radio", 2): ["technology", "home"],
    ("radio", 3): ["media", "technology"],
    ("radio", 4): ["media", "communication"],
    # relief
    ("relief", 1): ["health", "feelings"],
    ("relief", 2): ["safety", "environment"],
    ("relief", 3): ["military"],
    ("relief", 4): ["work", "military"],
    ("relief", 5): ["law", "finance"],
    ("relief", 6): ["feelings", "leisure"],
    ("relief", 7): ["arts"],
    ("relief", 8): ["arts", "general"],
    ("relief", 9): ["geography", "nature"],
    # railroad
    ("railroad", 1): ["transportation"],
    ("railroad", 2): ["transportation", "business"],
    ("railroad", 3): ["construction", "engineering"],
    ("railroad", 4): ["work", "management"],
    ("railroad", 5): ["law", "crime"],
    ("railroad", 6): ["travel", "transportation"],
    ("railroad", 7): ["work", "career"],
    # religion
    ("religion", 1): ["religion"],
    ("religion", 2): ["religion", "general"],
    # rain
    ("rain", 1): ["weather", "nature"],
    ("rain", 2): ["weather", "time"],
    ("rain", 3): ["geography", "nature"],
    ("rain", 4): ["weather", "nature"],
    # religious
    ("religious", 1): ["religion"],
    ("religious", 2): ["religion"],
    ("religious", 3): ["personality", "work"],
    ("religious", 4): ["religion"],
    # raise
    ("raise", 1): ["body", "daily life"],
    ("raise", 2): ["construction"],
    ("raise", 3): ["farming", "plants"],
    ("raise", 4): ["work", "communication"],
    ("raise", 5): ["general"],
    ("raise", 6): ["finance", "business"],
    ("raise", 7): ["communication", "social"],
    ("raise", 8): ["feelings", "emotions"],
    ("raise", 9): ["general"],
    ("raise", 10): ["communication", "music"],
    ("raise", 11): ["construction"],
    ("raise", 12): ["work", "career"],
    ("raise", 13): ["mining", "industry"],
    ("raise", 14): ["general"],
    ("raise", 15): ["finance", "military"],
    ("raise", 16): ["communication", "military"],
    ("raise", 17): ["military"],
    ("raise", 18): ["general"],
    ("raise", 19): ["clothing", "manufacturing"],
    ("raise", 20): ["general"],
    ("raise", 21): ["work", "finance"],
    ("raise", 22): ["leisure", "entertainment"],
    # rely
    ("rely", 1): ["relationships", "general"],
    # range
    ("range", 1): ["general"],
    ("range", 2): ["general", "work"],
    ("range", 3): ["general"],
    ("range", 4): ["military", "technology"],
    ("range", 5): ["military", "sports"],
    ("range", 6): ["home", "cooking"],
    ("range", 7): ["farming", "animals"],
    ("range", 8): ["geography", "general"],
    ("range", 9): ["general", "work"],
    ("range", 10): ["general", "work"],
    ("range", 11): ["politics", "general"],
    ("range", 12): ["travel", "nature"],
    ("range", 13): ["military"],
    ("range", 14): ["general"],
    ("range", 15): ["travel", "general"],
    ("range", 16): ["general"],
    ("range", 17): ["nature", "animals"],
    ("range", 18): ["military"],
    # remain
    ("remain", 1): ["general"],
    ("remain", 2): ["history"],
    ("remain", 3): ["literature", "history"],
    ("remain", 4): ["general", "religion"],
    ("remain", 5): ["general"],
    ("remain", 6): ["general"],
    # rank
    ("rank", 1): ["general"],
    ("rank", 2): ["military", "work"],
    ("rank", 3): ["general"],
    ("rank", 4): ["society", "social"],
    ("rank", 5): ["military", "work"],
    ("rank", 6): ["education", "science"],
    ("rank", 7): ["military"],
    ("rank", 8): ["general", "work"],
    ("rank", 9): ["military", "work"],
    ("rank", 10): ["general", "work"],
    ("rank", 11): ["military"],
    ("rank", 12): ["general"],
    ("rank", 13): ["farming", "plants"],
    ("rank", 14): ["general"],
    ("rank", 15): ["personality", "general"],
    ("rank", 16): ["general"],
    # remark
    ("remark", 1): ["communication", "general"],
    ("remark", 2): ["communication", "media"],
    ("remark", 3): ["general"],
    ("remark", 4): ["communication"],
    ("remark", 5): ["communication", "media"],
    # rapid
    ("rapid", 1): ["general"],
    ("rapid", 2): ["geography", "nature"],
    ("rapid", 3): ["geography", "nature"],
    # remember
    ("remember", 1): ["general", "education"],
    ("remember", 2): ["money", "work"],
    ("remember", 3): ["communication", "social"],
    ("remember", 4): ["religion"],
    # rapidly
    ("rapidly", 1): ["general"],
    ("rapidly", 2): ["geography", "nature"],
    ("rapidly", 3): ["geography", "nature"],
    # remind
    ("remind", 1): ["communication", "general"],
    # rare
    ("rare", 1): ["general"],
    ("rare", 2): ["food", "cooking"],
    ("rare", 3): ["general"],
    ("rare", 4): ["food", "cooking"],
    # remote
    ("remote", 1): ["geography", "travel"],
    ("remote", 2): ["personality", "social"],
    ("remote", 3): ["geography", "rural"],
    ("remote", 4): ["general"],
    # rarely
    ("rarely", 1): ["general"],
    ("rarely", 2): ["food", "cooking"],
    ("rarely", 3): ["general"],
    ("rarely", 4): ["food", "cooking"],
    # remove
    ("remove", 1): ["food", "restaurant"],
    ("remove", 2): ["education"],
    ("remove", 3): ["education"],
    ("remove", 4): ["general"],
    ("remove", 5): ["home", "daily life"],
    ("remove", 6): ["general"],
    ("remove", 7): ["work", "law"],
    ("remove", 8): ["general"],
    ("remove", 9): ["law", "crime"],
    ("remove", 10): ["crime", "military"],
    ("remove", 11): ["feelings", "health"],
    ("remove", 12): ["general"],
    ("remove", 13): ["general"],
    ("remove", 14): ["health", "medicine"],
    ("remove", 15): ["general"],
    ("remove", 16): ["home", "daily life"],
    # rate
    ("rate", 1): ["general", "finance"],
    ("rate", 2): ["general", "transportation"],
    ("rate", 3): ["finance", "money"],
    ("rate", 4): ["finance", "government"],
    ("rate", 5): ["general"],
    ("rate", 6): ["general", "work"],
    ("rate", 7): ["education"],
    ("rate", 8): ["home", "environment"],
    ("rate", 9): ["business", "finance"],
    ("rate", 10): ["general"],
    ("rate", 11): ["finance", "government"],
    ("rate", 12): ["transportation", "general"],
    ("rate", 13): ["education"],
    ("rate", 14): ["general"],
    ("rate", 15): ["communication", "feelings"],
    # rent
    ("rent", 1): ["home", "finance"],
    # rather
    ("rather", 1): ["general"],
    ("rather", 2): ["general", "feelings"],
    ("rather", 3): ["general"],
    ("rather", 4): ["general", "communication"],
    # repair
    ("repair", 1): ["home", "technology"],
    ("repair", 2): ["health"],
    ("repair", 3): ["general"],
    ("repair", 4): ["home", "technology"],
    ("repair", 5): ["general", "law"],
    ("repair", 6): ["law", "finance"],
    ("repair", 7): ["health"],
    ("repair", 8): ["general"],
    ("repair", 9): ["general"],
    ("repair", 10): ["travel", "daily life"],
    # raw
    ("raw", 1): ["food", "cooking"],
    ("raw", 2): ["general", "industry"],
    ("raw", 3): ["work", "career"],
    ("raw", 4): ["health", "body"],
    ("raw", 5): ["clothing", "design"],
    ("raw", 6): ["weather"],
    ("raw", 7): ["general"],
    ("raw", 8): ["law", "crime"],
    ("raw", 9): ["general"],
    ("raw", 10): ["health", "body"],
    ("raw", 11): ["health", "body"],
    # repeat
    ("repeat", 1): ["general", "education"],
    ("repeat", 2): ["music", "entertainment"],
    ("repeat", 3): ["music", "literature"],
    ("repeat", 4): ["media"],
    ("repeat", 5): ["business", "shopping"],
    ("repeat", 6): ["education"],
    ("repeat", 7): ["design", "arts"],
    ("repeat", 8): ["general", "education"],
    ("repeat", 9): ["general"],
    ("repeat", 10): ["education"],
    ("repeat", 11): ["communication", "literature"],
    ("repeat", 12): ["arts", "entertainment"],
    ("repeat", 13): ["general"],
    ("repeat", 14): ["food", "cooking"],
    ("repeat", 15): ["politics", "crime"],
    # reach
    ("reach", 1): ["general"],
    ("reach", 2): ["body", "general"],
    ("reach", 3): ["sports", "body"],
    ("reach", 4): ["education", "work"],
    ("reach", 5): ["geography", "general"],
    ("reach", 6): ["geography", "nature"],
    ("reach", 7): ["transportation", "sports"],
    ("reach", 8): ["body", "general"],
    ("reach", 9): ["body", "general"],
    ("reach", 10): ["travel", "general"],
    ("reach", 11): ["communication", "social"],
    ("reach", 12): ["social", "general"],
    ("reach", 13): ["general"],
    ("reach", 14): ["general"],
    ("reach", 15): ["travel", "general"],
    # repeated
    ("repeated", 1): ["general"],
    ("repeated", 2): ["general"],
    # react
    ("react", 1): ["general", "science"],
    ("react", 2): ["science", "education"],
    ("react", 3): ["general"],
    ("react", 4): ["military", "sports"],
    ("react", 5): ["finance", "business"],
    # replace
    ("replace", 1): ["general", "work"],
    ("replace", 2): ["general"],
    # reaction
    ("reaction", 1): ["health", "science"],
    ("reaction", 2): ["science", "education"],
    ("reaction", 3): ["politics"],
    ("reaction", 4): ["military", "sports"],
    # reply
    ("reply", 1): ["clothing", "home"],
    ("reply", 2): ["education"],
    ("reply", 3): ["informal", "social"],
    ("reply", 4): ["arts", "entertainment"],
    ("reply", 5): ["communication"],
    # read
    ("read", 1): ["education", "literature"],
    ("read", 2): ["education", "science"],
    ("read", 3): ["general"],
    ("read", 4): ["home", "finance"],
    ("read", 5): ["general"],
    ("read", 6): ["general"],
    ("read", 7): ["media", "education"],
    ("read", 8): ["general"],
    ("read", 9): ["general"],
    ("read", 10): ["general"],
    ("read", 11): ["education", "literature"],
    ("read", 12): ["education", "communication"],
    ("read", 13): ["education", "literature"],
    ("read", 14): ["general"],
    ("read", 15): ["education", "literature"],
    ("read", 16): ["education"],
    ("read", 17): ["education", "literature"],
    ("read", 18): ["education", "science"],
    ("read", 19): ["literature", "education"],
    ("read", 20): ["general"],
    ("read", 21): ["sleep", "daily life"],
    ("read", 22): ["personality", "general"],
    ("read", 23): ["general"],
    ("read", 24): ["education"],
    ("read", 25): ["literature", "media"],
    ("read", 26): ["leisure", "literature"],
    ("read", 27): ["general"],
    ("read", 28): ["general"],
    ("read", 29): ["education", "personality"],
    # report
    ("report", 1): ["work", "business"],
    ("report", 2): ["education", "media"],
    ("report", 3): ["media", "social"],
    ("report", 4): ["general", "social"],
    ("report", 5): ["military", "crime"],
    ("report", 6): ["communication"],
    ("report", 7): ["work", "business"],
    ("report", 8): ["media"],
    ("report", 9): ["media", "communication"],
    ("report", 10): ["law", "crime"],
    # reader
    ("reader", 1): ["literature", "media"],
    ("reader", 2): ["literature", "hobby"],
    ("reader", 3): ["education", "career"],
    ("reader", 4): ["media", "work"],
    ("reader", 5): ["religion"],
    ("reader", 6): ["media", "literature"],
    ("reader", 7): ["literature", "education"],
    ("reader", 8): ["education", "literature"],
    # reporter
    ("reporter", 1): ["media", "work"],
    ("reporter", 2): ["media"],
    # reading
    ("reading", 1): ["education", "literature"],
    ("reading", 2): ["education", "general"],
    ("reading", 3): ["government", "law"],
    ("reading", 4): ["literature", "education"],
    ("reading", 5): ["literature", "education"],
    ("reading", 6): ["general"],
    ("reading", 7): ["arts", "entertainment"],
    ("reading", 8): ["home", "technology"],
    # represent
    ("represent", 1): ["general"],
    ("represent", 2): ["work", "politics"],
    ("represent", 3): ["arts", "communication"],
    ("represent", 4): ["arts", "entertainment"],
    ("represent", 5): ["general"],
    # ready
    ("ready", 1): ["general"],
    ("ready", 2): ["feelings", "general"],
    ("ready", 3): ["general"],
    ("ready", 4): ["general"],
    ("ready", 5): ["general"],
    ("ready", 6): ["finance", "money"],
    ("ready", 7): ["general"],
    ("ready", 8): ["general"],
    ("ready", 9): ["general"],
    ("ready", 10): ["general"],
    ("ready", 11): ["general"],
    ("ready", 12): ["military"],
    ("ready", 13): ["finance", "money"],
    ("ready", 14): ["general"],
    ("ready", 15): ["finance", "money"],
    # representative
    ("representative", 1): ["arts", "general"],
    ("representative", 2): ["general", "politics"],
    ("representative", 3): ["government", "politics"],
    ("representative", 4): ["arts", "entertainment"],
    ("representative", 5): ["general"],
    ("representative", 6): ["work", "politics"],
    ("representative", 7): ["government", "politics"],
    # real
    ("real", 1): ["general"],
    ("real", 2): ["general"],
    ("real", 3): ["general"],
    ("real", 4): ["finance", "business"],
    ("real", 5): ["general"],
    # reputation
    ("reputation", 1): ["social", "general"],
    ("reputation", 2): ["social", "career"],
    # request
    ("request", 1): ["communication", "formal"],
    ("request", 2): ["business", "shopping"],
    ("request", 3): ["communication", "formal"],
    # require
    ("require", 1): ["general", "work"],
    # requirement
    ("requirement", 1): ["general", "work"],
    # rescue
    ("rescue", 1): ["safety"],
    ("rescue", 2): ["law", "crime"],
    ("rescue", 3): ["law", "crime"],
    ("rescue", 4): ["safety"],
    ("rescue", 5): ["law", "crime"],
    ("rescue", 6): ["law", "crime"],
    # research
    ("research", 1): ["science", "education"],
    ("research", 2): ["science", "education"],
    # researcher
    ("researcher", 1): ["science", "education"],
    # reservation
    ("reservation", 1): ["general"],
    ("reservation", 2): ["geography", "law"],
    ("reservation", 3): ["travel", "restaurant"],
    ("reservation", 4): ["general"],
    # reserve
    ("reserve", 1): ["general", "military"],
    ("reserve", 2): ["military"],
    ("reserve", 3): ["sports"],
    ("reserve", 4): ["personality", "general"],
    ("reserve", 5): ["personality"],
    ("reserve", 6): ["personality", "feelings"],
    ("reserve", 7): ["geography", "environment"],
    ("reserve", 8): ["general"],
    ("reserve", 9): ["travel", "restaurant"],
    ("reserve", 10): ["general"],
    ("reserve", 11): ["general"],
    # resident
    ("resident", 1): ["home", "daily life"],
    ("resident", 2): ["animals", "nature"],
    ("resident", 3): ["health", "education"],
    ("resident", 4): ["general"],
    ("resident", 5): ["home", "daily life"],
    ("resident", 6): ["government", "history"],
    ("resident", 7): ["animals", "nature"],
    # resist
    ("resist", 1): ["arts", "design"],
    ("resist", 2): ["general"],
    ("resist", 3): ["general"],
    ("resist", 4): ["general"],
    ("resist", 5): ["general"],
    # resolve
    ("resolve", 1): ["personality", "feelings"],
    ("resolve", 2): ["personality"],
    ("resolve", 3): ["general"],
    ("resolve", 4): ["general", "work"],
    ("resolve", 5): ["science", "general"],
    ("resolve", 6): ["crime", "health"],
    ("resolve", 7): ["music", "general"],
    ("resolve", 8): ["education"],
    ("resolve", 9): ["technology", "programming"],
    # resort
    ("resort", 1): ["general"],
    ("resort", 2): ["tourism", "travel"],
    ("resort", 3): ["general"],
    ("resort", 4): ["travel", "daily life"],
    # resource
    ("resource", 1): ["general"],
    ("resource", 2): ["environment", "economy"],
    ("resource", 3): ["economy", "military"],
    ("resource", 4): ["leisure", "entertainment"],
    ("resource", 5): ["general"],
    # respect
    ("respect", 1): ["social", "relationships"],
    ("respect", 2): ["communication", "formal"],
    ("respect", 3): ["general"],
    ("respect", 4): ["relationships", "general"],
    ("respect", 5): ["general"],
    ("respect", 6): ["social", "relationships"],
    ("respect", 7): ["general"],
    # respond
    ("respond", 1): ["general"],
    ("respond", 2): ["communication", "social"],
    # response
    ("response", 1): ["communication"],
    ("response", 2): ["communication", "general"],
    ("response", 3): ["health", "science"],
    ("response", 4): ["religion", "music"],
    # responsibility
    ("responsibility", 1): ["work", "general"],
    ("responsibility", 2): ["work", "general"],
    # responsible
    ("responsible", 1): ["work", "general"],
    ("responsible", 2): ["personality", "work"],
    # rest
    ("rest", 1): ["sleep", "health"],
    ("rest", 2): ["feelings", "health"],
    ("rest", 3): ["religion", "general"],
    ("rest", 4): ["general"],
    ("rest", 5): ["travel", "transportation"],
    ("rest", 6): ["home", "technology"],
    ("rest", 7): ["music", "general"],
    ("rest", 8): ["sleep", "health"],
    ("rest", 9): ["religion", "general"],
    ("rest", 10): ["general"],
    ("rest", 11): ["general"],
    ("rest", 12): ["general"],
    ("rest", 13): ["general"],
    ("rest", 14): ["health", "sleep"],
    ("rest", 15): ["general"],
    ("rest", 16): ["general"],
    ("rest", 17): ["general"],
    ("rest", 18): ["finance", "business"],
    ("rest", 19): ["finance", "business"],
    ("rest", 20): ["general"],
    ("rest", 21): ["general"],
    # restaurant
    ("restaurant", 1): ["restaurant", "food"],
    # result
    ("result", 1): ["general"],
    ("result", 2): ["education"],
    ("result", 3): ["general"],
    ("result", 4): ["general"],
    # retain
    ("retain", 1): ["general"],
    ("retain", 2): ["education", "general"],
    ("retain", 3): ["law", "work"],
    ("retain", 4): ["general"],
    # retire
    ("retire", 1): ["daily life", "home"],
    ("retire", 2): ["sleep", "daily life"],
    ("retire", 3): ["work", "career"],
    ("retire", 4): ["military", "general"],
    ("retire", 5): ["general", "sports"],
    ("retire", 6): ["work", "government"],
    ("retire", 7): ["military"],
    ("retire", 8): ["finance", "money"],
    ("retire", 9): ["military"],
    # retired
    ("retired", 1): ["general"],
    ("retired", 2): ["personality", "social"],
    ("retired", 3): ["rural", "geography"],
    ("retired", 4): ["work", "career"],
    # return
    ("return", 1): ["general", "travel"],
    ("return", 2): ["travel", "transportation"],
    ("return", 3): ["business", "shopping"],
    ("return", 4): ["business", "shopping"],
    ("return", 5): ["media", "business"],
    ("return", 6): ["business", "shopping"],
    ("return", 7): ["general"],
    ("return", 8): ["general"],
    ("return", 9): ["sports"],
    ("return", 10): ["sports"],
    ("return", 11): ["sports"],
    ("return", 12): ["general"],
    ("return", 13): ["construction", "home"],
    ("return", 14): ["general"],
    ("return", 15): ["finance", "business"],
    ("return", 16): ["finance", "money"],
    ("return", 17): ["work", "business"],
    ("return", 18): ["politics", "government"],
    ("return", 19): ["daily life", "health"],
    ("return", 20): ["travel", "general"],
    ("return", 21): ["business", "general"],
    ("return", 22): ["business", "shopping"],
    ("return", 23): ["general", "sports"],
    ("return", 24): ["communication", "social"],
    ("return", 25): ["communication"],
    ("return", 26): ["general"],
    ("return", 27): ["law", "government"],
    ("return", 28): ["business", "finance"],
    ("return", 29): ["politics", "government"],
    ("return", 30): ["military"],
    # reveal
    ("reveal", 1): ["general", "media"],
    ("reveal", 2): ["general"],
    # review
    ("review", 1): ["law"],
    ("review", 2): ["military"],
    ("review", 3): ["general", "military"],
    ("review", 4): ["literature", "media"],
    ("review", 5): ["media", "literature"],
    ("review", 6): ["law"],
    ("review", 7): ["law", "government"],
    ("review", 8): ["military"],
    ("review", 9): ["general", "military"],
    ("review", 10): ["literature", "media"],
    ("review", 11): ["literature", "media"],
    # revise
    ("revise", 1): ["education", "general"],
    ("revise", 2): ["law", "education"],
    # revolution
    ("revolution", 1): ["general"],
    ("revolution", 2): ["science"],
    ("revolution", 3): ["politics", "history"],
    # reward
    ("reward", 1): ["general", "work"],
    ("reward", 2): ["crime", "money"],
    ("reward", 3): ["law", "finance"],
    ("reward", 4): ["general", "work"],
    # rhythm
    ("rhythm", 1): ["music", "literature"],
    ("rhythm", 2): ["general", "body"],
    # rice
    ("rice", 1): ["food", "farming"],
    ("rice", 2): ["plants", "farming"],
    # rich
    ("rich", 1): ["money", "finance"],
    ("rich", 2): ["general"],
    ("rich", 3): ["appearance", "clothing"],
    ("rich", 4): ["food", "cooking"],
    ("rich", 5): ["appearance", "arts"],
    ("rich", 6): ["entertainment", "feelings"],
    # rid
    ("rid", 1): ["general"],
    # ride
    ("ride", 1): ["travel", "leisure"],
    ("ride", 2): ["travel", "nature"],
    ("ride", 3): ["military"],
    ("ride", 4): ["sports", "leisure"],
    ("ride", 5): ["general"],
    ("ride", 6): ["transportation", "travel"],
    ("ride", 7): ["general"],
    ("ride", 8): ["transportation", "travel"],
    ("ride", 9): ["general"],
    ("ride", 10): ["clothing", "sports"],
    ("ride", 11): ["sports", "animals"],
    ("ride", 12): ["sports", "travel"],
    ("ride", 13): ["general"],
    ("ride", 14): ["general"],
    ("ride", 15): ["feelings", "general"],
    ("ride", 16): ["sports", "nature"],
    # right
    ("right", 1): ["philosophy", "general"],
    ("right", 2): ["law", "politics"],
    ("right", 3): ["law", "politics"],
    ("right", 4): ["general"],
    ("right", 5): ["general"],
    ("right", 6): ["body", "general"],
    ("right", 7): ["politics"],
    ("right", 8): ["sports"],
    ("right", 9): ["military"],
    ("right", 10): ["general"],
    ("right", 11): ["general"],
    ("right", 12): ["general"],
    ("right", 13): ["politics"],
    ("right", 14): ["general"],
    ("right", 15): ["health", "general"],
    ("right", 16): ["general"],
    ("right", 17): ["general"],
    ("right", 18): ["general"],
    ("right", 19): ["general"],
    ("right", 20): ["general"],
    ("right", 21): ["general"],
    ("right", 22): ["general"],
    ("right", 23): ["transportation"],
    ("right", 24): ["general"],
    ("right", 25): ["law", "general"],
    ("right", 26): ["transportation"],
    # ring1
    ("ring1", 1): ["clothing"],
    ("ring1", 2): ["general"],
    ("ring1", 3): ["general"],
    ("ring1", 4): ["sports", "entertainment"],
    ("ring1", 5): ["sports"],
    ("ring1", 6): ["entertainment", "arts"],
    ("ring1", 7): ["general"],
    ("ring1", 8): ["body", "nature"],
    ("ring1", 9): ["general"],
    ("ring1", 10): ["work", "business"],
    ("ring1", 11): ["politics"],
    ("ring1", 12): ["sports", "crime"],
    ("ring1", 13): ["general"],
    ("ring1", 14): ["plants", "nature"],
    ("ring1", 15): ["clothing", "daily life"],
    ("ring1", 16): ["animals", "farming"],
    ("ring1", 17): ["general"],
    ("ring1", 18): ["animals", "general"],
    ("ring1", 19): ["food", "cooking"],
    ("ring1", 20): ["animals", "nature"],
    ("ring1", 21): ["animals", "nature"],
    ("ring1", 22): ["religion", "music"],
    ("ring1", 23): ["general"],
    ("ring1", 24): ["technology", "communication"],
    ("ring1", 25): ["general"],
    ("ring1", 26): ["general"],
    ("ring1", 27): ["general"],
    ("ring1", 28): ["general"],
    ("ring1", 29): ["general"],
    ("ring1", 30): ["general"],
    ("ring1", 31): ["health", "body"],
    ("ring1", 32): ["general"],
    ("ring1", 33): ["general"],
    ("ring1", 34): ["general"],
    ("ring1", 35): ["finance", "crime"],
    # ring2
    ("ring2", 1): ["clothing"],
    ("ring2", 2): ["general"],
    ("ring2", 3): ["general"],
    ("ring2", 4): ["sports", "entertainment"],
    ("ring2", 5): ["sports"],
    ("ring2", 6): ["entertainment", "arts"],
    ("ring2", 7): ["general"],
    ("ring2", 8): ["body", "nature"],
    ("ring2", 9): ["general"],
    ("ring2", 10): ["work", "business"],
    ("ring2", 11): ["politics"],
    ("ring2", 12): ["sports", "crime"],
    ("ring2", 13): ["general"],
    ("ring2", 14): ["plants", "nature"],
    ("ring2", 15): ["clothing", "daily life"],
    ("ring2", 16): ["animals", "farming"],
    ("ring2", 17): ["general"],
    ("ring2", 18): ["animals", "general"],
    ("ring2", 19): ["food", "cooking"],
    ("ring2", 20): ["animals", "nature"],
    ("ring2", 21): ["animals", "nature"],
    ("ring2", 22): ["religion", "music"],
    ("ring2", 23): ["general"],
    ("ring2", 24): ["technology", "communication"],
    ("ring2", 25): ["general"],
    ("ring2", 26): ["general"],
    ("ring2", 27): ["general"],
    ("ring2", 28): ["general"],
    ("ring2", 29): ["general"],
    ("ring2", 30): ["general"],
    ("ring2", 31): ["health", "body"],
    ("ring2", 32): ["general"],
    ("ring2", 33): ["general"],
    ("ring2", 34): ["general"],
    ("ring2", 35): ["finance", "crime"],
    # rise
    ("rise", 1): ["general"],
    ("rise", 2): ["work", "finance"],
    ("rise", 3): ["work", "career"],
    ("rise", 4): ["animals", "nature"],
    ("rise", 5): ["sports", "travel"],
    ("rise", 6): ["geography", "nature"],
    ("rise", 7): ["general"],
    ("rise", 8): ["general"],
    ("rise", 9): ["daily life", "body"],
    ("rise", 10): ["nature", "science"],
    ("rise", 11): ["general"],
    ("rise", 12): ["success", "career"],
    ("rise", 13): ["general"],
    ("rise", 14): ["politics", "military"],
    ("rise", 15): ["feelings", "emotions"],
    ("rise", 16): ["general"],
    ("rise", 17): ["general"],
    ("rise", 18): ["work", "formal"],
    ("rise", 19): ["general"],
    ("rise", 20): ["general"],
    # risk
    ("risk", 1): ["general"],
    ("risk", 2): ["safety", "general"],
    ("risk", 3): ["general"],
    ("risk", 4): ["safety", "general"],
    # river
    ("river", 1): ["nature", "geography"],
    ("river", 2): ["nature", "general"],
    ("river", 3): ["philosophy", "religion"],
    ("river", 4): ["nature", "geography"],
    # road
    ("road", 1): ["transportation", "travel"],
    ("road", 2): ["transportation"],
    ("road", 3): ["urban", "transportation"],
    ("road", 4): ["general"],
    ("road", 5): ["transportation", "travel"],
    ("road", 6): ["animals", "sports"],
    # robot
    ("robot", 1): ["technology", "science"],
    ("robot", 2): ["technology", "general"],
    # rock
    ("rock", 1): ["nature", "geography"],
    ("rock", 2): ["money", "informal"],
    ("rock", 3): ["food"],
    ("rock", 4): ["animals", "nature"],
    ("rock", 5): ["general"],
    ("rock", 6): ["general"],
    ("rock", 7): ["general"],
    ("rock", 8): ["general"],
    # role
    ("role", 1): ["work", "general"],
    # roll
    ("roll", 1): ["general"],
    ("roll", 2): ["food"],
    ("roll", 3): ["work", "law"],
    ("roll", 4): ["general"],
    ("roll", 5): ["general"],
    ("roll", 6): ["money", "informal"],
    ("roll", 7): ["engineering", "technology"],
    ("roll", 8): ["general"],
    ("roll", 9): ["transportation", "general"],
    ("roll", 10): ["nature", "general"],
    ("roll", 11): ["music", "general"],
    ("roll", 12): ["transportation", "technology"],
    ("roll", 13): ["general"],
    ("roll", 14): ["general"],
    ("roll", 15): ["music", "literature"],
    ("roll", 16): ["industry", "general"],
    ("roll", 17): ["general"],
    ("roll", 18): ["general"],
    ("roll", 19): ["science", "nature"],
    ("roll", 20): ["general"],
    ("roll", 21): ["time", "general"],
    ("roll", 22): ["transportation"],
    ("roll", 23): ["nature", "general"],
    ("roll", 24): ["transportation", "general"],
    ("roll", 25): ["music", "general"],
    ("roll", 26): ["industry", "general"],
    ("roll", 27): ["transportation", "sports"],
    # romantic
    ("romantic", 1): ["literature", "arts"],
    ("romantic", 2): ["general"],
    ("romantic", 3): ["literature", "arts"],
    ("romantic", 4): ["literature", "arts"],
    # roof
    ("roof", 1): ["home", "construction"],
    ("roof", 2): ["general"],
    ("roof", 3): ["transportation", "technology"],
    ("roof", 4): ["transportation", "technology"],
    ("roof", 5): ["construction", "home"],
    ("roof", 6): ["home", "construction"],
    # room
    ("room", 1): ["home", "daily life"],
    ("room", 2): ["general"],
    ("room", 3): ["home", "daily life"],
    ("room", 4): ["general"],
    ("room", 5): ["general"],
    ("room", 6): ["home", "daily life"],
    ("room", 7): ["home", "daily life"],
    # root
    ("root", 1): ["plants", "nature"],
    ("root", 2): ["plants", "farming"],
    ("root", 3): ["plants", "food"],
    ("root", 4): ["general"],
    ("root", 5): ["general"],
    ("root", 6): ["education", "general"],
    ("root", 7): ["education"],
    ("root", 8): ["music", "general"],
    ("root", 9): ["family", "general"],
    ("root", 10): ["plants", "farming"],
    ("root", 11): ["general"],
    ("root", 12): ["general"],
    ("root", 13): ["general"],
    ("root", 14): ["general"],
    ("root", 15): ["sports", "social"],
    # rope
    ("rope", 1): ["general"],
    ("rope", 2): ["sports", "entertainment"],
    ("rope", 3): ["general"],
    ("rope", 4): ["general"],
    ("rope", 5): ["general"],
    ("rope", 6): ["sports", "safety"],
    ("rope", 7): ["sports", "crime"],
    ("rope", 8): ["food", "general"],
    ("rope", 9): ["sports"],
    # rough
    ("rough", 1): ["general"],
    ("rough", 2): ["weather", "nature"],
    ("rough", 3): ["general"],
    ("rough", 4): ["personality", "informal"],
    ("rough", 5): ["general"],
    ("rough", 6): ["general"],
    ("rough", 7): ["general"],
    ("rough", 8): ["personality", "informal"],
    ("rough", 9): ["geography", "nature"],
    ("rough", 10): ["animals", "sports"],
    ("rough", 11): ["general"],
    ("rough", 12): ["crime", "informal"],
    ("rough", 13): ["general"],
    ("rough", 14): ["general"],
    ("rough", 15): ["sports"],
    ("rough", 16): ["body", "general"],
    ("rough", 17): ["animals", "sports"],
    ("rough", 18): ["arts", "design"],
    ("rough", 19): ["animals", "sports"],
    ("rough", 20): ["general"],
    ("rough", 21): ["music"],
    # round
    ("round", 1): ["general"],
    ("round", 2): ["general"],
    ("round", 3): ["general"],
    ("round", 4): ["general"],
    ("round", 5): ["personality", "informal"],
    ("round", 6): ["music", "general"],
    ("round", 7): ["literature", "general"],
    ("round", 8): ["general"],
    ("round", 9): ["general"],
    ("round", 10): ["general"],
    ("round", 11): ["general"],
    ("round", 12): ["general"],
    ("round", 13): ["general"],
    ("round", 14): ["military", "travel"],
    ("round", 15): ["social", "food"],
    ("round", 16): ["sports", "entertainment"],
    ("round", 17): ["general"],
    ("round", 18): ["home", "general"],
    ("round", 19): ["military"],
    ("round", 20): ["military"],
    ("round", 21): ["general"],
    ("round", 22): ["general"],
    ("round", 23): ["general"],
    ("round", 24): ["general"],
    ("round", 25): ["general"],
    ("round", 26): ["general"],
    ("round", 27): ["travel", "geography"],
    ("round", 28): ["literature", "general"],
    ("round", 29): ["general"],
    ("round", 30): ["finance", "money"],
    ("round", 31): ["general"],
    # route
    ("route", 1): ["transportation", "travel"],
    ("route", 2): ["military"],
    ("route", 3): ["business", "transportation"],
    # routine
    ("routine", 1): ["daily life", "work"],
    ("routine", 2): ["general", "work"],
    ("routine", 3): ["entertainment", "arts"],
    # row1
    ("row1", 1): ["general"],
    ("row1", 2): ["home", "urban"],
    ("row1", 3): ["entertainment", "arts"],
    ("row1", 4): ["farming", "plants"],
    ("row1", 5): ["sports", "leisure"],
    ("row1", 6): ["sports"],
    ("row1", 7): ["sports", "transportation"],
    ("row1", 8): ["sports", "competition"],
    ("row1", 9): ["sports", "general"],
    ("row1", 10): ["sports"],
    ("row1", 11): ["sports"],
    ("row1", 12): ["general"],
    ("row1", 13): ["crime", "social"],
    ("row1", 14): ["communication", "work"],
    ("row1", 15): ["communication", "work"],
    ("row1", 16): ["general"],
    ("row1", 17): ["crime", "social"],
    # royal
    ("royal", 1): ["government", "history"],
    ("royal", 2): ["government", "history"],
    ("royal", 3): ["formal", "appearance"],
    ("royal", 4): ["government", "history"],
    ("royal", 5): ["animals", "nature"],
    ("royal", 6): ["military", "transportation"],
    ("royal", 7): ["military", "history"],
    # rub
    ("rub", 1): ["general"],
    ("rub", 2): ["daily life", "general"],
    ("rub", 3): ["sports", "general"],
    ("rub", 4): ["general"],
    ("rub", 5): ["general"],
    ("rub", 6): ["body", "daily life"],
    ("rub", 7): ["daily life", "general"],
    ("rub", 8): ["arts", "design"],
    ("rub", 9): ["food", "cooking"],
    ("rub", 10): ["general"],
    ("rub", 11): ["clothing", "body"],
    ("rub", 12): ["sports", "general"],
    # rubber
    ("rubber", 1): ["industry", "technology"],
    ("rubber", 2): ["education"],
    ("rubber", 3): ["clothing", "daily life"],
    ("rubber", 4): ["health", "work"],
    ("rubber", 5): ["daily life", "general"],
    ("rubber", 6): ["general"],
    ("rubber", 7): ["general"],
    ("rubber", 8): ["informal", "general"],
    ("rubber", 9): ["feelings", "general"],
    # rude
    ("rude", 1): ["informal", "social"],
    ("rude", 2): ["general"],
    ("rude", 3): ["informal", "social"],
    ("rude", 4): ["general"],
    ("rude", 5): ["health", "body"],
    # rule
    ("rule", 1): ["law", "general"],
    ("rule", 2): ["daily life", "general"],
    ("rule", 3): ["government", "politics"],
    ("rule", 4): ["government", "politics"],
    ("rule", 5): ["work", "design"],
    ("rule", 6): ["law"],
    ("rule", 7): ["literature", "education"],
    ("rule", 8): ["government", "politics"],
    ("rule", 9): ["general"],
    ("rule", 10): ["education", "general"],
    ("rule", 11): ["law", "government"],
    ("rule", 12): ["work", "design"],
    ("rule", 13): ["government", "politics"],
    ("rule", 14): ["general"],
    # run
    ("run", 1): ["sports", "exercise"],
    ("run", 2): ["travel", "leisure"],
    ("run", 3): ["transportation", "travel"],
    ("run", 4): ["technology", "work"],
    ("run", 5): ["finance", "general"],
    ("run", 6): ["time", "general"],
    ("run", 7): ["general"],
    ("run", 8): ["business", "shopping"],
    ("run", 9): ["animals", "nature"],
    ("run", 10): ["farming", "animals"],
    ("run", 11): ["animals", "nature"],
    ("run", 12): ["home", "nature"],
    ("run", 13): ["nature", "geography"],
    ("run", 14): ["general"],
    ("run", 15): ["literature", "music"],
    ("run", 16): ["general"],
    ("run", 17): ["business", "shopping"],
    ("run", 18): ["general"],
    ("run", 19): ["military"],
    ("run", 20): ["geography", "nature"],
    ("run", 21): ["transportation", "technology"],
    ("run", 22): ["general"],
    ("run", 23): ["sports", "exercise"],
    ("run", 24): ["general"],
    ("run", 25): ["crime", "general"],
    ("run", 26): ["sports", "competition"],
    ("run", 27): ["technology", "work"],
    ("run", 28): ["general"],
    ("run", 29): ["general"],
    ("run", 30): ["plants", "nature"],
    ("run", 31): ["sports", "general"],
    ("run", 32): ["literature", "general"],
    ("run", 33): ["time", "general"],
    ("run", 34): ["law", "general"],
    ("run", 35): ["feelings", "general"],
    ("run", 36): ["general"],
    ("run", 37): ["general"],
    ("run", 38): ["general"],
    ("run", 39): ["transportation"],
    ("run", 40): ["general"],
    ("run", 41): ["general"],
    ("run", 42): ["general"],
    ("run", 43): ["home", "general"],
    ("run", 44): ["general"],
    ("run", 45): ["general"],
    ("run", 46): ["general"],
    ("run", 47): ["animals", "nature"],
    ("run", 48): ["politics"],
    ("run", 49): ["sports", "exercise"],
    ("run", 50): ["sports", "competition"],
    ("run", 51): ["general"],
    ("run", 52): ["general"],
    ("run", 53): ["general"],
    ("run", 54): ["general"],
    ("run", 55): ["animals", "sports"],
    ("run", 56): ["industry", "general"],
    ("run", 57): ["work", "management"],
    ("run", 58): ["general"],
    ("run", 59): ["general"],
    ("run", 60): ["general"],
    ("run", 61): ["general"],
    ("run", 62): ["general"],
    ("run", 63): ["farming", "animals"],
    ("run", 64): ["crime", "business"],
    ("run", 65): ["clothing", "work"],
    ("run", 66): ["work", "technology"],
    ("run", 67): ["finance", "general"],
    ("run", 68): ["general"],
    ("run", 69): ["politics"],
    # runner
    ("runner", 1): ["finance", "business"],
    ("runner", 2): ["sports"],
    ("runner", 3): ["crime", "business"],
    ("runner", 4): ["home", "technology"],
    ("runner", 5): ["animals", "nature"],
    ("runner", 6): ["technology", "work"],
    ("runner", 7): ["military", "crime"],
    ("runner", 8): ["animals", "nature"],
    ("runner", 9): ["home", "cooking"],
    ("runner", 10): ["technology", "general"],
    ("runner", 11): ["technology", "general"],
    ("runner", 12): ["transportation", "work"],
    ("runner", 13): ["crime", "law"],
    # running
    ("running", 1): ["sports", "competition"],
    ("running", 2): ["technology", "work"],
    ("running", 3): ["general"],
    ("running", 4): ["crime", "business"],
    ("running", 5): ["military"],
    ("running", 6): ["work", "management"],
    ("running", 7): ["sports", "exercise"],
    ("running", 8): ["general"],
    ("running", 9): ["general"],
    ("running", 10): ["time", "general"],
    # rural
    ("rural", 1): ["rural", "geography"],
    # rush
    ("rush", 1): ["plants", "nature"],
    ("rush", 2): ["general"],
    ("rush", 3): ["nature", "general"],
    ("rush", 4): ["business", "shopping"],
    ("rush", 5): ["general", "time"],
    ("rush", 6): ["general"],
    ("rush", 7): ["general"],
    ("rush", 8): ["military"],
    ("rush", 9): ["sports"],
    ("rush", 10): ["general", "time"],
    ("rush", 11): ["general"],
    ("rush", 12): ["general"],
    ("rush", 13): ["general", "time"],
    ("rush", 14): ["nature", "general"],
    ("rush", 15): ["general"],
    ("rush", 16): ["general"],
    ("rush", 17): ["military"],
    ("rush", 18): ["crime", "business"],
    ("rush", 19): ["business", "work"],
    ("rush", 20): ["general"],
    # sad
    ("sad", 1): ["feelings", "emotions"],
    ("sad", 2): ["general"],
    ("sad", 3): ["food", "cooking"],
    ("sad", 4): ["general"],
    # sadly
    ("sadly", 1): ["feelings", "emotions"],
    ("sadly", 2): ["general"],
    ("sadly", 3): ["food", "cooking"],
    ("sadly", 4): ["general"],
    # safe
    ("safe", 1): ["food", "home"],
    ("safe", 2): ["home", "finance"],
    ("safe", 3): ["safety", "general"],
    ("safe", 4): ["safety", "general"],
    ("safe", 5): ["safety", "general"],
    # safety
    ("safety", 1): ["safety", "general"],
    ("safety", 2): ["safety", "general"],
    ("safety", 3): ["safety", "military"],
    # sail
    ("sail", 1): ["transportation", "nature"],
    ("sail", 2): ["transportation", "travel"],
    ("sail", 3): ["technology", "nature"],
    ("sail", 4): ["technology", "work"],
    ("sail", 5): ["travel", "leisure"],
    ("sail", 6): ["transportation", "travel"],
    ("sail", 7): ["travel", "transportation"],
    ("sail", 8): ["nature", "general"],
    ("sail", 9): ["general"],
    ("sail", 10): ["transportation", "nature"],
    ("sail", 11): ["transportation", "travel"],
    # sailing
    ("sailing", 1): ["education"],
    ("sailing", 2): ["travel", "leisure"],
    ("sailing", 3): ["travel", "transportation"],
    # sailor
    ("sailor", 1): ["transportation", "work"],
    # salad
    ("salad", 1): ["food", "cooking"],
    ("salad", 2): ["food", "cooking"],
    ("salad", 3): ["food", "cooking"],
    # salary
    ("salary", 1): ["work", "finance"],
    ("salary", 2): ["work", "finance"],
    # sale
    ("sale", 1): ["business", "shopping"],
    ("sale", 2): ["business", "shopping"],
    ("sale", 3): ["business", "shopping"],
    # salt
    ("salt", 1): ["food", "cooking"],
    ("salt", 2): ["communication", "general"],
    ("salt", 3): ["nature", "geography"],
    ("salt", 4): ["food", "cooking"],
    ("salt", 5): ["transportation", "work"],
    ("salt", 6): ["nature", "environment"],
    ("salt", 7): ["food", "cooking"],
    ("salt", 8): ["plants", "nature"],
    ("salt", 9): ["feelings", "general"],
    ("salt", 10): ["communication", "general"],
    ("salt", 11): ["informal", "general"],
    ("salt", 12): ["business", "finance"],
    ("salt", 13): ["food", "cooking"],
    ("salt", 14): ["communication", "general"],
    # same
    ("same", 1): ["general"],
    ("same", 2): ["general"],
    ("same", 3): ["general"],
    ("same", 4): ["general"],
    ("same", 5): ["general"],
    ("same", 6): ["general"],
    ("same", 7): ["general"],
    ("same", 8): ["general"],
    # sample
    ("sample", 1): ["business", "shopping"],
    ("sample", 2): ["business", "shopping"],
    ("sample", 3): ["general"],
    # sand
    ("sand", 1): ["nature", "geography"],
    ("sand", 2): ["nature", "geography"],
    ("sand", 3): ["personality", "general"],
    ("sand", 4): ["general"],
    ("sand", 5): ["general"],
    ("sand", 6): ["crime", "business"],
    ("sand", 7): ["general"],
    # sandwich
    ("sandwich", 1): ["food", "cooking"],
    ("sandwich", 2): ["general"],
    ("sandwich", 3): ["work", "advertising"],
    ("sandwich", 4): ["general"],
    # satellite
    ("satellite", 1): ["technology", "science"],
    ("satellite", 2): ["work", "general"],
    ("satellite", 3): ["politics", "government"],
    ("satellite", 4): ["general"],
    # satisfied
    ("satisfied", 1): ["feelings", "emotions"],
    ("satisfied", 2): ["general"],
    # satisfy
    ("satisfy", 1): ["feelings", "general"],
    ("satisfy", 2): ["feelings", "general"],
    ("satisfy", 3): ["finance", "law"],
    ("satisfy", 4): ["general"],
    # Saturday
    ("Saturday", 1): ["time", "daily life"],
    # sauce
    ("sauce", 1): ["food", "cooking"],
    ("sauce", 2): ["general"],
    ("sauce", 3): ["food", "cooking"],
    ("sauce", 4): ["informal", "social"],
    ("sauce", 5): ["food", "cooking"],
    ("sauce", 6): ["food", "cooking"],
    ("sauce", 7): ["food", "cooking"],
    ("sauce", 8): ["informal", "social"],
    # save
    ("save", 1): ["sports"],
    ("save", 2): ["safety"],
    ("save", 3): ["sports"],
    ("save", 4): ["safety"],
    ("save", 5): ["finance", "money"],
    ("save", 6): ["finance", "money"],
    ("save", 7): ["time", "general"],
    ("save", 8): ["technology", "computing"],
    ("save", 9): ["general"],
    ("save", 10): ["general"],
    ("save", 11): ["general"],
    ("save", 12): ["general"],
    ("save", 13): ["general"],
    ("save", 14): ["finance", "money"],
    ("save", 15): ["general"],
    ("save", 16): ["general"],
    ("save", 17): ["general"],
    ("save", 18): ["general"],
    # saving
    ("saving", 1): ["finance", "money"],
    ("saving", 2): ["finance", "money"],
    # say
    ("say", 1): ["clothing", "textile"],
    ("say", 2): ["communication", "general"],
    ("say", 3): ["communication", "general"],
    ("say", 4): ["general"],
    ("say", 5): ["communication", "general"],
    ("say", 6): ["general"],
    ("say", 7): ["general"],
    ("say", 8): ["general"],
    # scale
    ("scale", 1): ["animals", "nature"],
    ("scale", 2): ["animals", "nature"],
    ("scale", 3): ["animals", "nature"],
    ("scale", 4): ["technology", "industry"],
    ("scale", 5): ["health", "body"],
    ("scale", 6): ["animals", "nature"],
    ("scale", 7): ["technology", "industry"],
    ("scale", 8): ["health", "body"],
    ("scale", 9): ["animals", "nature"],
    ("scale", 10): ["technology", "general"],
    ("scale", 11): ["technology", "general"],
    ("scale", 12): ["general"],
    ("scale", 13): ["music"],
    ("scale", 14): ["general", "measurement"],
    ("scale", 15): ["sports", "exercise"],
    ("scale", 16): ["geography", "design"],
    ("scale", 17): ["general", "measurement"],
    ("scale", 18): ["general"],
    # scan
    ("scan", 1): ["literature", "education"],
    ("scan", 2): ["literature", "education"],
    ("scan", 3): ["literature", "education"],
    ("scan", 4): ["general"],
    ("scan", 5): ["general"],
    ("scan", 6): ["technology", "media"],
    ("scan", 7): ["technology", "medicine"],
    # scared
    ("scared", 1): ["general"],
    ("scared", 2): ["feelings", "emotions"],
    # scary
    ("scary", 1): ["feelings", "emotions"],
    # scene
    ("scene", 1): ["general"],
    ("scene", 2): ["arts", "entertainment"],
    ("scene", 3): ["arts", "entertainment"],
    ("scene", 4): ["nature", "general"],
    ("scene", 5): ["social", "general"],
    ("scene", 6): ["arts", "entertainment"],
    # schedule
    ("schedule", 1): ["work", "general"],
    ("schedule", 2): ["work", "time"],
    ("schedule", 3): ["work", "time"],
    ("schedule", 4): ["work", "general"],
    ("schedule", 5): ["work", "time"],
    ("schedule", 6): ["work", "time"],
    # school
    ("school", 1): ["education"],
    ("school", 2): ["education"],
    ("school", 3): ["education"],
    ("school", 4): ["animals", "nature"],
    ("school", 5): ["general"],
    ("school", 6): ["education", "history"],
    ("school", 7): ["education"],
    ("school", 8): ["education"],
    ("school", 9): ["education"],
    ("school", 10): ["education"],
    ("school", 11): ["education"],
    ("school", 12): ["education"],
    ("school", 13): ["music", "education"],
    ("school", 14): ["animals", "nature"],
    ("school", 15): ["education"],
    # science
    ("science", 1): ["science", "education"],
    ("science", 2): ["science", "education"],
    ("science", 3): ["science", "education"],
    ("science", 4): ["science", "engineering"],
    ("science", 5): ["science", "education"],
    # scientific
    ("scientific", 1): ["science", "education"],
    ("scientific", 2): ["science", "engineering"],
    # scientist
    ("scientist", 1): ["science", "education"],
    ("scientist", 2): ["science", "education"],
    # score
    ("score", 1): ["sports", "competition"],
    ("score", 2): ["general"],
    ("score", 3): ["finance", "law"],
    ("score", 4): ["music", "arts"],
    ("score", 5): ["general"],
    ("score", 6): ["general"],
    ("score", 7): ["general"],
    ("score", 8): ["general"],
    ("score", 9): ["general"],
    ("score", 10): ["sports", "competition"],
    ("score", 11): ["sports", "competition"],
    ("score", 12): ["general"],
    ("score", 13): ["finance", "law"],
    ("score", 14): ["general"],
    ("score", 15): ["music", "arts"],
    ("score", 16): ["communication", "general"],
    # scream
    ("scream", 1): ["feelings", "emotions"],
    ("scream", 2): ["entertainment", "feelings"],
    ("scream", 3): ["entertainment", "feelings"],
    ("scream", 4): ["feelings", "emotions"],
    ("scream", 5): ["entertainment", "feelings"],
    # screen
    ("screen", 1): ["home", "furniture"],
    ("screen", 2): ["technology", "general"],
    ("screen", 3): ["technology", "general"],
    ("screen", 4): ["media", "entertainment"],
    ("screen", 5): ["industry", "technology"],
    ("screen", 6): ["general"],
    ("screen", 7): ["media", "entertainment"],
    ("screen", 8): ["industry", "technology"],
    ("screen", 9): ["work", "career"],
    ("screen", 10): ["media", "entertainment"],
    # script
    ("script", 1): ["media", "entertainment"],
    ("script", 2): ["design", "arts"],
    ("script", 3): ["media", "entertainment"],
    ("script", 4): ["design", "arts"],
    ("script", 5): ["media", "entertainment"],
    ("script", 6): ["technology", "programming"],
    # sculpture
    ("sculpture", 1): ["arts"],
    ("sculpture", 2): ["arts"],
    ("sculpture", 3): ["arts", "nature"],
    ("sculpture", 4): ["arts"],
    ("sculpture", 5): ["arts"],
    ("sculpture", 6): ["arts", "nature"],
    # sea
    ("sea", 1): ["nature", "geography"],
    ("sea", 2): ["nature", "geography"],
    ("sea", 3): ["nature", "general"],
    # search
    ("search", 1): ["general"],
    ("search", 2): ["general"],
    ("search", 3): ["general"],
    ("search", 4): ["general"],
    ("search", 5): ["general"],
    ("search", 6): ["military"],
    ("search", 7): ["general"],
    # season
    ("season", 1): ["weather", "time"],
    ("season", 2): ["general", "time"],
    ("season", 3): ["general", "time"],
    ("season", 4): ["general"],
    ("season", 5): ["food", "cooking"],
    ("season", 6): ["general"],
    # seat
    ("seat", 1): ["home", "furniture"],
    ("seat", 2): ["home", "furniture"],
    ("seat", 3): ["body"],
    ("seat", 4): ["clothing"],
    ("seat", 5): ["general"],
    ("seat", 6): ["home", "general"],
    ("seat", 7): ["general"],
    ("seat", 8): ["general"],
    ("seat", 9): ["general"],
    ("seat", 10): ["general"],
    ("seat", 11): ["general"],
    ("seat", 12): ["general"],
    ("seat", 13): ["general"],
    ("seat", 14): ["politics", "government"],
    # second1
    ("second1", 1): ["general", "time"],
    ("second1", 2): ["general"],
    ("second1", 3): ["sports", "competition"],
    ("second1", 4): ["time"],
    ("second1", 5): ["time"],
    ("second1", 6): ["time"],
    ("second1", 7): ["general"],
    ("second1", 8): ["sports"],
    ("second1", 9): ["general"],
    ("second1", 10): ["general"],
    ("second1", 11): ["sports"],
    ("second1", 12): ["food", "cooking"],
    ("second1", 13): ["transportation"],
    ("second1", 14): ["general"],
    ("second1", 15): ["general"],
    ("second1", 16): ["military"],
    ("second1", 17): ["military"],
    ("second1", 18): ["military"],
    ("second1", 19): ["military"],
    # secondary
    ("secondary", 1): ["general"],
    ("secondary", 2): ["science"],
    ("secondary", 3): ["education"],
    ("secondary", 4): ["science"],
    ("secondary", 5): ["work", "general"],
    ("secondary", 6): ["religion"],
    ("secondary", 7): ["science"],
    ("secondary", 8): ["animals", "nature"],
    ("secondary", 9): ["science"],
}

# Generate output
lines = []
for item in data:
    word = item['word']
    for i, meaning in enumerate(item['meanings'], 1):
        key = (word, i)
        if key in labels:
            label_str = ", ".join(labels[key])
        else:
            label_str = "general"
        lines.append(f"{word}\t{i}\t{label_str}")

# Write output
with open('E:/vibe_coding/english-app/ctx_parts/run3/chunk_14.txt', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')

print(f"Generated {len(lines)} lines")
print(f"Words: {len(data)}")
print(f"Total meanings: {total_meanings}")
